---

- name: Install dumb init
  get_url:
    dest: /usr/bin/dumb-init
    url: https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64
    mode: 0775
    validate_certs: no

- name: Install EPEL
  yum: name=epel-release state=latest

- name: Install OpenResty Dependencies
  yum: name=luarocks,lua-devel,readline-devel,pcre-devel,openssl-devel,gcc,curl state=latest

- name: Add OpenResty Repo
  yum_repository:
    name: openresty
    description: OpenResty Open Source Repository for CentOS
    file: external_repos
    baseurl: https://openresty.org/package/centos/$releasever/$basearch/
    gpgkey:  https://openresty.org/package/pubkey.gpg
    gpgcheck: yes

- name: Install OpenResty
  yum: name=openresty,openresty-resty state=latest
